### ISSUE TITLE
Source release?

### ISSUE THREAD

**Issue by olsonanl** [ncbi/sra-human-scrubber#1]
Hi- I am interested in evaluating this tool but cannot run docker in our production environment and there doesn't appear to be a release available here. Will one be coming out soon?

Thanks,
Bob Olson
ANL

**Comment by multikengineer** [comment]
@olsonanl my apologies. I have pushed an initial feature branch,  and will create a master branch tomorrow.
Bob - can you run a singularity container in your production env?

**Comment by olsonanl** [comment]
Great - thank you. Yes, we use singularity extensively in our cluster.

I did build a singularity container from the docker version; however, our production nodes are still running CentOS 6 and the resulting container isn't compatible with C6.

**Comment by multikengineer** [comment]
Thanks Bob..  Yes, the container was build on Debian. I can somewhat easily build it on a centos7 host (and see that it works). It would not be easy for me to build it on centos6, let alone getting approval to do so.  Any chance your nodes might get upgraded soon?

**Comment by olsonanl** [comment]
It’s in plan. If you have the sources such that I can build from scratch I should be able to build out the tool in my environment (I have a large collection of bioinformatic software already in place here).

**Comment by multikengineer** [comment]
You can see the repo has scripts, and a binary compiled app. It is possible to in fact build that binary from a different repo (nfs-tools) if the binary won't run on your host.

**Comment by olsonanl** [comment]
Cool. I will give this a shot this week and let you know how it goes
