### ISSUE TITLE
Is there a protocol for creating a custom database?

### ISSUE THREAD

**Issue by rpetit3** [ncbi/sra-human-scrubber#12]
I realize this is a human scrubber, but I'm curious, let's say I wanted to create a `aligns_to` database for the mouse genome. Is there a protocol for than, or do you have code used to create the human database?

**Comment by multikengineer** [comment]
@rpetit3  - absolutely: look at the manuscript link at the top of the readme here, or for a quick start to https://github.com/ncbi/ngs-tools/tree/tax/tools/tax
Have a great weekend.

**Comment by rpetit3** [comment]
Awesome! Thank you very much, enjoy your weekend too!
