### ISSUE TITLE
Best method to determine current sra-human-scrubber version?

### ISSUE THREAD

**Issue by rpetit3** [ncbi/sra-human-scrubber#14]
How would you suggest users easily determine the current version?

Do you think something like  `scrub.sh --version` would be possible in the next version?

**Comment by multikengineer** [comment]
Yes I can add something to surface it.  The output of course already prints the aligns_to version, and I am going to add a db version tag in the next release as well.

**Comment by rpetit3** [comment]
Awesome, thank you very much!

**Comment by multikengineer** [comment]
Robert - 2.1.0 will output scrubber db version  when running test.  Hope that suffices, and sorry it took so long.
