### ISSUE TITLE
custom database

### ISSUE THREAD

**Issue by manolis2023** [ncbi/sra-human-scrubber#20]
Hi,

how can I create a custom database? Do you have any command or example?

Best

**Comment by multikengineer** [comment]
Apologies for having missed this, and I now owe you **two** wishes for a Happy St. Valentine's Day.  To build a database you will want tools found in [this repo ](https://github.com/ncbi/ngs-tools), and specifically look at [this example](https://github.com/ncbi/ngs-tools/blob/master/tools/tax/examples/build_db_and_run.sh).
