### ISSUE TITLE
Source code? 

### ISSUE THREAD

**Issue by accopeland** [ncbi/sra-human-scrubber#21]
Is or will source code for this tool be made available?

**Comment by multikengineer** [comment]
Alex, I am guessing the source code you refer to is for the binary aligns_to: yes it is available here: 
https://github.com/ncbi/ngs-tools/tree/tax/tools/tax/src
However aligns_to (and perhaps other tools in that directory) are planned to move to a different ncbi GitHub repo in the near future.

**Comment by accopeland** [comment]
Thank you.

**Comment by accopeland** [comment]
Closing as resolved
