### ISSUE TITLE
HRRT on ONT data

### ISSUE THREAD

**Issue by cimendes** [ncbi/sra-human-scrubber#30]
Hello!

I was wondering how appropriate it is to run HRRT on long-read data such as ONT? I'm having a hard time finding any information regarding this subject. Thank you so much!

**Comment by multikengineer** [comment]
Input is fastq  and I presume you can use pore-tools or some similar code to generate fastq.   I can't think of any reason whey it would not be appropriate as it doesn't care about read length. The efficiency may (or may not) be different for ONT compared to Illumina.

**Comment by cimendes** [comment]
Thank you for the clarification! :D
