### ISSUE TITLE
please version the database

### ISSUE THREAD

**Issue by pvanheus** [ncbi/sra-human-scrubber#5]
The current database is at https://ftp.ncbi.nlm.nih.gov/sra/dbs/human_filter.db and lacks any identifiable version information. Please provide a database version so that it is possible to know when the DB is updated.

If you could also provide a database "schema" version so that if there is ever a non-backwards compatible update of the DB (so that some versions of the DB can only be used with some versions of the tool), that would also be useful, thanks!

**Comment by multikengineer** [comment]
Please forgive the tardy reply.
>The current database is at https://ftp.ncbi.nlm.nih.gov/sra/dbs/human_filter.db and lacks any identifiable version information. Please provide a database version so that it is possible to know when the DB is updated.

Good suggestion, and when the DB is updated I will version it accordingly.

>If you could also provide a database "schema" version so that if there is ever a non-backwards compatible update of the DB (so that some versions of the DB can only be used with some versions of the tool), that would also be useful, thanks!

The database does have a schema version embedded so a non-backwards compatible update will report the non compatible version.

**Comment by multikengineer** [comment]
Along with release of tag 2.0.0 there is a versioning of the database used (as distinct from the internal schema version).
By default the init_db.sh script will pull the current version, and the docker image is built using that same script.
See https://ftp.ncbi.nlm.nih.gov/sra/dbs/human_filter/
